
name: CI/CD
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
env:
  JABBA_INDEX: 'https://github.com/typelevel/jdk-index/raw/main/index.json'
jobs:
  test:
    name: test ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [temurin@11, temurin@17]
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: ${{ matrix.java }}
      - run: ./mill __.test
  
  publish:
    needs: test
    if: ((branch = main AND type = push) OR (tag IS present)) AND NOT fork
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Publish to Maven Central
        run: ./mill io.kipp.mill.ci.release.ReleaseModule/publishAll
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

